name: master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # 00:00 Sunday

jobs:

  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Test rayon
        run: cargo test --verbose --package rayon
      - name: Test rayon-core
        run: cargo test --verbose --package rayon-core
      - name: Test multiple rayon-core
        run: ./ci/highlander.sh
